#pragma once

#define LEFT_FRONT_PORT 12
#define RIGHT_FRONT_PORT 2
#define LEFT_BACK_PORT 11
#define RIGHT_BACK_PORT 2
#define ROBOT_LENGTH 18.0
#define TICKS_PER_INCH 1555
#define ROLLER_MOTOR_PORT 5