#pragma once

#define ROBOT_LENGTH 18.0
#define TICKS_PER_INCH 1555

#define LEFT_BACK_PORT 1
#define LEFT_FRONT_PORT 2
#define RIGHT_BACK_PORT 12
#define RIGHT_FRONT_PORT 11
#define ROLLER_PORT 7
#define ROLLER_VOLTAGE 75
#define LAUNCHER_PORT 8
#define RELEASE_PORT 20

#define FLYWHEEL_LEFT 4
#define FLYWHEEL_RIGHT 5
