#pragma once
#define LEFT_BACK_PORT 12
#define LEFT_FRONT_PORT 11
#define RIGHT_BACK_PORT 2
#define RIGHT_FRONT_PORT 1
#define ROLLER_PORT 5
#define ROLLER_VOLTAGE 75
#define ROBOT_LENGTH 18.0
#define TICKS_PER_INCH 1555
#define ROLLER_MOTOR_PORT 5
